/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/solid-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as authAuthImport } from './routes/(auth)/auth'
import { Route as appSettingsImport } from './routes/(app)/settings'
import { Route as appTasksCreateImport } from './routes/(app)/tasks/create'
import { Route as appHomeExplorerImport } from './routes/(app)/home/_explorer'
import { Route as authAuthSigninIndexImport } from './routes/(auth)/auth/signin/index'
import { Route as authAuthSigninMagicLinkImport } from './routes/(auth)/auth/signin/magic-link'
import { Route as appHomeExplorerSplatImport } from './routes/(app)/home/_explorer/$'

// Create Virtual Routes

const appHomeImport = createFileRoute('/(app)/home')()

// Create/Update Routes

const appHomeRoute = appHomeImport.update({
  id: '/(app)/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const appIndexRoute = appIndexImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/(auth)/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const appSettingsRoute = appSettingsImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const appTasksCreateRoute = appTasksCreateImport.update({
  id: '/(app)/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => rootRoute,
} as any)

const appHomeExplorerRoute = appHomeExplorerImport.update({
  id: '/_explorer',
  getParentRoute: () => appHomeRoute,
} as any)

const authAuthSigninIndexRoute = authAuthSigninIndexImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthSigninMagicLinkRoute = authAuthSigninMagicLinkImport.update({
  id: '/signin/magic-link',
  path: '/signin/magic-link',
  getParentRoute: () => authAuthRoute,
} as any)

const appHomeExplorerSplatRoute = appHomeExplorerSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => appHomeExplorerRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof rootRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/home': {
      id: '/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeImport
      parentRoute: typeof rootRoute
    }
    '/(app)/home/_explorer': {
      id: '/(app)/home/_explorer'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeExplorerImport
      parentRoute: typeof appHomeRoute
    }
    '/(app)/tasks/create': {
      id: '/(app)/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof appTasksCreateImport
      parentRoute: typeof rootRoute
    }
    '/(app)/home/_explorer/$': {
      id: '/(app)/home/_explorer/$'
      path: '/$'
      fullPath: '/home/$'
      preLoaderRoute: typeof appHomeExplorerSplatImport
      parentRoute: typeof appHomeExplorerImport
    }
    '/(auth)/auth/signin/magic-link': {
      id: '/(auth)/auth/signin/magic-link'
      path: '/signin/magic-link'
      fullPath: '/auth/signin/magic-link'
      preLoaderRoute: typeof authAuthSigninMagicLinkImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/auth/signin/': {
      id: '/(auth)/auth/signin/'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof authAuthSigninIndexImport
      parentRoute: typeof authAuthImport
    }
  }
}

// Create and export the route tree

interface authAuthRouteChildren {
  authAuthSigninMagicLinkRoute: typeof authAuthSigninMagicLinkRoute
  authAuthSigninIndexRoute: typeof authAuthSigninIndexRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthSigninMagicLinkRoute: authAuthSigninMagicLinkRoute,
  authAuthSigninIndexRoute: authAuthSigninIndexRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface appHomeExplorerRouteChildren {
  appHomeExplorerSplatRoute: typeof appHomeExplorerSplatRoute
}

const appHomeExplorerRouteChildren: appHomeExplorerRouteChildren = {
  appHomeExplorerSplatRoute: appHomeExplorerSplatRoute,
}

const appHomeExplorerRouteWithChildren = appHomeExplorerRoute._addFileChildren(
  appHomeExplorerRouteChildren,
)

interface appHomeRouteChildren {
  appHomeExplorerRoute: typeof appHomeExplorerRouteWithChildren
}

const appHomeRouteChildren: appHomeRouteChildren = {
  appHomeExplorerRoute: appHomeExplorerRouteWithChildren,
}

const appHomeRouteWithChildren =
  appHomeRoute._addFileChildren(appHomeRouteChildren)

export interface FileRoutesByFullPath {
  '/settings': typeof appSettingsRoute
  '/auth': typeof authAuthRouteWithChildren
  '/': typeof appIndexRoute
  '/home': typeof appHomeExplorerRouteWithChildren
  '/tasks/create': typeof appTasksCreateRoute
  '/home/$': typeof appHomeExplorerSplatRoute
  '/auth/signin/magic-link': typeof authAuthSigninMagicLinkRoute
  '/auth/signin': typeof authAuthSigninIndexRoute
}

export interface FileRoutesByTo {
  '/settings': typeof appSettingsRoute
  '/auth': typeof authAuthRouteWithChildren
  '/': typeof appIndexRoute
  '/home': typeof appHomeExplorerRouteWithChildren
  '/tasks/create': typeof appTasksCreateRoute
  '/home/$': typeof appHomeExplorerSplatRoute
  '/auth/signin/magic-link': typeof authAuthSigninMagicLinkRoute
  '/auth/signin': typeof authAuthSigninIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/auth': typeof authAuthRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(app)/home': typeof appHomeRouteWithChildren
  '/(app)/home/_explorer': typeof appHomeExplorerRouteWithChildren
  '/(app)/tasks/create': typeof appTasksCreateRoute
  '/(app)/home/_explorer/$': typeof appHomeExplorerSplatRoute
  '/(auth)/auth/signin/magic-link': typeof authAuthSigninMagicLinkRoute
  '/(auth)/auth/signin/': typeof authAuthSigninIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/auth'
    | '/'
    | '/home'
    | '/tasks/create'
    | '/home/$'
    | '/auth/signin/magic-link'
    | '/auth/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/auth'
    | '/'
    | '/home'
    | '/tasks/create'
    | '/home/$'
    | '/auth/signin/magic-link'
    | '/auth/signin'
  id:
    | '__root__'
    | '/(app)/settings'
    | '/(auth)/auth'
    | '/(app)/'
    | '/(app)/home'
    | '/(app)/home/_explorer'
    | '/(app)/tasks/create'
    | '/(app)/home/_explorer/$'
    | '/(auth)/auth/signin/magic-link'
    | '/(auth)/auth/signin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appSettingsRoute: typeof appSettingsRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  appIndexRoute: typeof appIndexRoute
  appHomeRoute: typeof appHomeRouteWithChildren
  appTasksCreateRoute: typeof appTasksCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  appSettingsRoute: appSettingsRoute,
  authAuthRoute: authAuthRouteWithChildren,
  appIndexRoute: appIndexRoute,
  appHomeRoute: appHomeRouteWithChildren,
  appTasksCreateRoute: appTasksCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)/settings",
        "/(auth)/auth",
        "/(app)/",
        "/(app)/home",
        "/(app)/tasks/create"
      ]
    },
    "/(app)/settings": {
      "filePath": "(app)/settings.tsx"
    },
    "/(auth)/auth": {
      "filePath": "(auth)/auth.tsx",
      "children": [
        "/(auth)/auth/signin/magic-link",
        "/(auth)/auth/signin/"
      ]
    },
    "/(app)/": {
      "filePath": "(app)/index.tsx"
    },
    "/(app)/home": {
      "filePath": "(app)/home",
      "children": [
        "/(app)/home/_explorer"
      ]
    },
    "/(app)/home/_explorer": {
      "filePath": "(app)/home/_explorer.tsx",
      "parent": "/(app)/home",
      "children": [
        "/(app)/home/_explorer/$"
      ]
    },
    "/(app)/tasks/create": {
      "filePath": "(app)/tasks/create.tsx"
    },
    "/(app)/home/_explorer/$": {
      "filePath": "(app)/home/_explorer/$.tsx",
      "parent": "/(app)/home/_explorer"
    },
    "/(auth)/auth/signin/magic-link": {
      "filePath": "(auth)/auth/signin/magic-link.tsx",
      "parent": "/(auth)/auth"
    },
    "/(auth)/auth/signin/": {
      "filePath": "(auth)/auth/signin/index.tsx",
      "parent": "/(auth)/auth"
    }
  }
}
ROUTE_MANIFEST_END */
